name: Release Build

on:
  release:
    types: [published] # Triggers when a new GitHub Release is published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy docker-compose and JAR to output folder
        run: |
          mkdir release
          cp docker-compose.yml release/
          cp target/*.jar release/

      - name: Archive release files
        run: |
          cd release
          zip -r ../release-bundle.zip .

      - name: Upload release bundle to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
